default_language_version:
    python: python3.9
default_stages: [commit, push]

repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      #- id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: ["-b, master", "-b, test", "-b, main", "-b, homo", "-b, prod"]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/pycqa/flake8 # https://flake8.pycqa.org/en/latest/user/error-codes.html
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--config=.flake8]

  - repo: https://github.com/pycqa/pylint
    rev: v3.2.5
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc, --exit-zero]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8


  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.9'
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml", "-r", "."]
        additional_dependencies: [ "bandit[toml]" ]


#  - repo: https://github.com/PyCQA/prospector
#    rev: 1.1.7 # The version of Prospector to use, at least 1.1.7
#    hooks:
#      - id: prospector

#  - repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        language: system
#        stages: [push]
#        entry: sh -c pytest --rootdir tests
#        files: \.py$
#        pass_filenames: false
