[tool.black]
line-length = 79

[tool.pycln]
all = true

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
allow_redefinition = true
ignore_missing_imports = false
implicit_reexport = true
show_error_codes = true
strict_optional = false
pretty = true

[tool.bandit]
exclude_dirs = ["tests", "venv"]
skips = ["B101", "B110"]
